# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image: gitpod/workspace-full
tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y ccache gcc gfortran g++ openmpi-bin libopenmpi-dev \
      python3 python3-pip python3-setuptools
      sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 2
      sudo update-alternatives --set python /usr/bin/python3
      python -m pip install --upgrade pip
      python -m pip install --upgrade wheel
      python -m pip install --upgrade cmake matplotlib==3.2.2 numpy yt
# Ports to expose on workspace startup (optional)
ports:
  - port: 8000
    onOpen: open-preview
  - port: 8888
    onOpen: open-browser
