# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image: gitpod/workspace-full
tasks:
- init: /workspace/ecp-tutorials/dependencies.sh
  command: cp -r /workspace/ecp-tutorials/.jupyter /home/gitpod/
# Ports to expose on workspace startup (optional)
ports:
  - port: 8000
    onOpen: open-preview
  - port: 8888
    onOpen: open-browser
